services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:3333"
      - "5555:5555"
    env_file:
      - ./.env
    volumes:
      - ./server:/usr/src/app
      - server_node_modules:/usr/src/app/node_modules
    command: npm run start:dev
    depends_on:
      db: 
        condition: service_healthy 

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_PORT}:5173"
    env_file:
      - ./.env
    volumes:
      - ./client:/usr/src/app
      # REMOVIDA A LINHA DO NODE_MODULES AQUI PARA EVITAR CONFLITOS
      - /usr/src/app/node_modules
    # Adicionado --host para garantir acesso externo
    command: npm run dev -- --host

  db:
    container_name: devflow_db
    image: postgres:15
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - ./.env
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgresql_data: {}
  server_node_modules: {}